from src.tabs.tabs_unit_comb.tabs_unit_comb import TABSUnitComb
from src.tabs.tabs_unit_deploy.tabs_unit_deploy import TABSUnitDeploy
from src.tabs.tabs_battle_simulator.tabs_battle_simulator import TABSBattleSimulator
